### ISSUE TITLE
Tooltips in Eclipse

### ISSUE THREAD

**Issue by Heterodyne** [mate-desktop/mate-themes#165] opened 2017-03-11 20:39 UTC
The tooltips that display using Menta theme in Eclipse are unreadable (almost black text on black background).
Although tooltip background color is defined as  #F5F5B5 in settings.ini, this is not honored (in Eclipse).
Other themes I've tried (including Adwana) behave properly. (dark text and light background).
I can add  
.tooltip * {
    background-color: transparent;
}
to at least be able to read the text (lighter text on black background) this is not the answer.

![screenshot from 2017-03-11 15 36 04](https://cloud.githubusercontent.com/assets/11461036/23826729/d10426b8-0670-11e7-9b4d-3d4688d6780a.png)

**Comment by sc0w** [comment] 2017-04-10 23:33
I have installed eclipse (3.8.1), and apparently I can see tooltips normally with menta:

![eclipsetooltip](https://cloud.githubusercontent.com/assets/7734191/24886515/5f011c36-1e55-11e7-86b2-f4cc45496c57.png)

**Comment by raveit65** [comment] 2017-04-11 05:53
Same here in fedora 26 (gtk+-3.22)
![bildschirmfoto zu 2017-04-11 07-45-49](https://cloud.githubusercontent.com/assets/961604/24894498/0420ad96-1e8b-11e7-9555-d334e2d11b62.png)
![bildschirmfoto zu 2017-04-11 07-51-06](https://cloud.githubusercontent.com/assets/961604/24894590/a7f6688e-1e8b-11e7-8071-4ec444985282.png)
@Heterodyne 
Does the issue still exists?

**Comment by sc0w** [comment] 2017-05-30 16:04
no answer, I think we can close this

**Comment by raveit65** [comment] 2017-05-30 16:14
I bet we will get an answer if i close it ;-)

**Comment by Heterodyne** [comment] 2017-06-17 16:00
All tooltips look legible. Inside the eclipse editor I see white text on black now (better contract than dark grey on black!). The other tool tips look as shown above (black on yellow)...  
So yes ... can close!

**Comment by Heterodyne** [comment] 2017-06-17 20:24
Curiously, if I add ... 
```
tooltip.background {
   background-color: @theme_tooltip_bg_color
}
```
to the end of gtk-widgets-backgrounds.css I get the desired result (yellow background)

I say curiously because this is already in gtk_widgets.css
```
tooltip.background,
.tooltip.background {
        background-color: @theme_tooltip_bg_color;
    background-clip: padding-box;
}
```

**Comment by lukefromdc** [comment] 2017-06-18 01:22
Anything that themes tooltip.background lower in the file than those lines first
appear could be overriding it. It would be in the same file or you could not reset
it within gtk-widgets.css, and it should not be  a matter of something more specific 
overriding it either. Later in a file overrides earlier in the file, and more specific
overrides less specific.

**Comment by Heterodyne** [comment] 2017-06-18 16:44
There's something curious going on ...  I get a black tooltip background if I use the unmodified theme, or if I add the following to `gtk-widget-backgrounds.css`
```
@define-color theme_tooltip_bg_color #F5F5B5;
tooltip.background,
.tooltip.background {
    background-color: @theme_tooltip_bg_color;
    background-clip: padding-box;
}
![bad-menta eclipsetooltip](https://user-images.githubusercontent.com/11461036/27262378-7da85e98-5423-11e7-8e4d-03990b11f465.png)

If I explicitly define the color it works ...
tooltip.background,
.tooltip.background {
    background-color: #F5F5B5;
    background-clip: padding-box;
}
![ok-menta eclipsetooltip](https://user-images.githubusercontent.com/11461036/27262382-9cd9ae84-5423-11e7-923c-ad912c973c6a.png)

Its as if something (eclipse ?) is overriding the definition of the background color (theme_tooltip_bg_color)
```

**Comment by lukefromdc** [comment] 2017-06-18 18:09
I just found that in Menta,  theme_tooltip_bg_color is used in gtk-widgets.css, is defined not in gtk-main.css but gtk-main-common.css . I wonder if this is somehow causing the problems?  I don't have eclipse installed but copying everything in gtk-main-common.css to the bottom of gtk-main.css would test this. There is no reason in the world this should be an issue or should fix anything-unless a bug in GTK is responsible. That's what this test is looking for.

**Comment by Heterodyne** [comment] 2017-06-18 18:15
... I don't think this is the problem because even if you define the color immediately before using it is ignored ..
```
@define-color theme_tooltip_bg_color #F5F5B5;
tooltip.background,
.tooltip.background {
    background-color: @theme_tooltip_bg_color;
    background-clip: padding-box;
}
```

**Comment by lukefromdc** [comment] 2017-06-18 18:20
That sounds like to make Eclipse work right it may just be necessary to bite the bullet and hardcode this color directly for tooltips in gtk-widgets.css. Since tooltips look the same in Menta and BlueMenta this should not create a maintainance problem but it should be commented.

**Comment by Heterodyne** [comment] 2017-06-18 23:20
It wouldn't surprise me to find that eclipse is actually using the css directly (and not using a gtk widget). If it's expecting standard css then the gtk-3 specific @define-color definition is ignored

**Comment by raveit65** [comment] 2017-06-19 10:49
Well, there is a different between using **theme** in color definition or not but i forgot.........
Does this work ?
```
@define-color tooltip_bg_color #F5F5B5;
tooltip.background,
.tooltip.background {
    background-color: @tooltip_bg_color;
    background-clip: padding-box;
}
```
And i don't use  Eclipse. Can you please explain detailed how to reproduce the issue?
As you can see in my sceenshot i have a yellow background.
Btw. which distro ,gtk+3 version and mate-themes version are you using?

**Comment by Heterodyne** [comment] 2017-06-19 14:41
No, changing from theme_tooltip_bg_color to tooltip_bg_color didn't make any difference.
The tooltip you are showing is in the general frame of the eclipse workspace, and yes I too see that as OK with the theme as is. 
The problem with tooltips specifically occurs in the editor window (all the examples that I have shown are within the editor window). It may occur in other components as well but this is where I see it.

I don't know why there is a difference between the general eclipse frame components and the editor component but the behavior is different. Also to make matters more complicated, even within the editor there are several tooltip types. When the problem is evident, there are some types of tooltips that have a black background (as seen above) and some with a white background. When the actual value is used in Menta css (background-color: #F5F5B5;) then both of these have a yellow background.

**Comment by raveit65** [comment] 2017-06-19 15:10
Ok, i am fine with with using a hardcoded color definition for theme_tooltip_bg_color in gtk-widget.css,
As this definition is only used for tooltips and nothing else.
Does this work if you edit gtk-widget.css here https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/Menta/gtk-3.0/gtk-widgets.css#L133
If yes, i will commit that.

**Comment by Heterodyne** [comment] 2017-06-19 15:52
Yes, simply replacing (in gtk-widgets.css)
`       background-color: @theme_tooltip_bg_color;`
with 
`       background-color:  #F5F5B5;`
where you indicated does solve the issue

**Comment by Heterodyne** [comment] 2017-06-20 01:30
After all that I see that this issue may become moot with the next eclipse (Oxygen)
[(http://www.eclipse.org/oxygen/noteworthy/#platform-linux)]

Consistent Javadoc colors usage under Linux

The Javadoc color usage on Linux was inconsistent since GTK 3.04. This has been resolved and support for Javadoc on the Eclipse Dark Theme has been added.

Before:
![i1](https://user-images.githubusercontent.com/11461036/27312469-7ed6316e-5536-11e7-912e-00c8709cab73.png)
After:
![i2](https://user-images.githubusercontent.com/11461036/27312474-8529a5a0-5536-11e7-9d0b-f01870fa48e3.png)

**Comment by lukefromdc** [comment] 2017-06-20 01:40
This document shows we are indeed dealing with a direct read of a GTK theme's css and not with GTK itself. As such, it's a bug in Eclipse (that they intend to fix) and not really in our theme unless we explicitly support the current version of Eclipse(a 1 line change).

**Closed** 2017-06-20 05:06 UTC

**Comment by raveit65** [comment] 2017-06-20 05:12
@Heterodyne 
Can you please give us a hint if this work arround isn't needed any more?
But i am guessing we have to live with it for years because of always old and obsoleted debian ;-)

**Comment by Heterodyne** [comment] 2017-06-20 17:16
I would say yes ...  Until the new Eclipse (Oxygen) is available I'm not able to test whether the issue is actually fixed. In any case the older versions will be around for some time so the fix is relevant.

From a philosophical perspective  since this is **really** an Eclipse issue I wouldn't blame you for not changing it. Then again, since it wouldn't have any second order effects, it would be a nice thing to do 8-)
