### ISSUE TITLE
TraditionalOK: Panel has different background from applets

### ISSUE THREAD

**Issue by mar-kolya** [mate-desktop/mate-themes#200] opened 2017-12-31 02:52 UTC
#### Expected behaviour

Panel and applets` background should match

#### Actual behaviour

Panel and applets background do not match:
![panel](https://user-images.githubusercontent.com/1003102/34458726-5a311956-edab-11e7-97f1-7b875b5c7c77.png)

#### Steps to reproduce the behaviour

Select TraditionalOk as a theme and use weather or sensors applet. The problem also exists with traditional mate menu. It looks like TraditionalGreen theme is affected as well.

#### MATE general version

1.18

#### Package version

3.22.14-1ubuntu0 

#### Linux Distribution

Ubuntu 17.10

**Comment by sc0w** [comment] 2018-04-17 23:43
Seems it was already fixed, with git master I can't reproduce the issue

**Comment by sc0w** [comment] 2018-04-20 09:03
Fixed with https://github.com/mate-desktop/mate-themes/commit/2969b74fc7a79284547f3839948dfe5be9fe7ac9 in mate-themes 3.22.16

**Closed by sc0w** 2018-04-20 09:03 UTC
Labels: confirmed
