### ISSUE TITLE
Firefox context menu - no selection in Menta and BlueMenta themes

### ISSUE THREAD

**Issue by direwolfie** [mate-desktop/mate-themes#118] opened 2016-04-30 13:52 UTC
**Setup** - Arch Linux x64 - MATE 1.12.1 GTK2 - mate-themes 3.20.5-2
Firefox 45.0.2/46 (GTK3 enabled)
**Affected themes** - Menta, BlueMenta, Blue-Submarine, Green-Submarine.

**Prerequisites** - there is a need to change the default GTK3 theme.
Add `export GTK_THEME=BlueMenta` (or just Menta) to _.xprofile_ in the Home folder. Log out and then log back in for the setting to take effect. (At least this is how I changed the theme).

**Steps to reproduce**
1. Open Firefox
2. Right-click anywhere on the page
3. Move cursor to any context menu item

**Expected result**
Context menu item is highlighted when cursor is hovering over the item.
**Actual result**
Context menu item is not highlighted BUT the text color changes as in screenshot.

**Notes:** This issue does not affect other GTK3 programs.
The default Adwaita theme does not have this problem.

**Comment by lukefromdc** [comment] 2016-05-01 03:14
Just confirmed this for the submarine themes and Menta: BlackMATE , TraditionalGreen, TraditionalOK, and GreenLaguna are good, I also have this fixed in my UbuntuStudio_Legacy theme with similar code.The submarine themes have this problem in ALL menus made by Firefox, I think they just haven't gotten some of the Firefox specific theming that is being done theme by theme yet.

There is one menu though that no theme works in: that popover menu made by the history button. None of the usual Firefox style class fixes work for it-and even glob selectors have minimal effect. Suspect something hardcoded or being overridden somewhere on that menu only.

Firefox does not use GTK in the normal manner, neither does LibreOffice. These are both crucial programs but very complex programs loaded with hard to theme custom widgets, especially in GTK 3.20.

**Comment by raveit65** [comment] 2016-05-02 17:13
I don't see that with Menta/Submarine themes and any other theme from latest git, not released yet.
Ie. on this github site the context menuitem have the right color with hover state. 
Please test themes from latest 3.20 branch.

> Prerequisites - there is a need to change the default GTK3 theme.
> Add export GTK_THEME=BlueMenta (or just Menta) to .xprofile in the Home folder. Log out and then log back in for the setting to take effect. (At least this is how I changed the theme).

This isn't needed if you use MATE Desktop, here you can switch the theme via mate-control-center.
Looks like a problem other desktops with gtk+
I suggest to use /usr/share and not ~.local/

**Comment by direwolfie** [comment] 2016-05-04 06:49
> This isn't needed if you use MATE Desktop, here you can switch the theme via mate-control-center.
> Looks like a problem other desktops with gtk+
> I suggest to use /usr/share and not ~.local/

You are right, this is not needed.
I did this when I was running a theme not compatible with GTK3, because GTK3 would default to Adwaita.

> Please test themes from latest 3.20 branch.
Isn't Arch on the latest branch already (3.20.5-2)?

**Comment by raveit65** [comment] 2016-05-04 08:08
> I guess it will be fixed in Arch in the next few releases.

 yes, i will prepare a new release soon.

**Closed by raveit65** 2016-05-04 08:08 UTC
Labels: unconfirmed

**Comment by direwolfie** [comment] 2016-06-03 12:05
> yes, i will prepare a new release soon.

Great! thanks!
