### ISSUE TITLE
Sometimes text is unreadable in BlackMATE

### ISSUE THREAD

**Issue by laszlowaty** [mate-desktop/mate-themes#110] opened 2016-03-25 21:00 UTC
In blackmate, sometimes when background is white, text-font-color is white as well making it unreadable. This problem occurs with python's tkinter and ubuntu-software-center (and sometimes in other tooltips popups). Is there any workaround or fix to this problem?

Examples:
![image](https://cloud.githubusercontent.com/assets/11692724/14053874/b981721c-f2d4-11e5-9fd9-00dfd67804b9.png)
![image](https://cloud.githubusercontent.com/assets/11692724/14053890/db8c84e6-f2d4-11e5-9338-e7ae6a66c05e.png)
##

**Comment by lukefromdc** [comment] 2016-03-26 01:49
Tkinter is a different toolkit, BlackMATE is a GTK theme. I don't know if there
are modules in Tkinter to attempt to follow GTK themes or not. I do know that
QT can use GTK2 themes but has issues with them.  Dark themes give a lot
of trouble, apparently my "UbuntuStudio_Legacy" or it's 2008 era progenitor
are among the only ones usable with it. This problem is so bad that the Kdenlive
devs set their program up to ignore GTK themes unless the user explicitly
selects them, due to complaints about unreadable text in so many of the
dark themes favored by those of us who edit video. In my theme only tooltip
and some versions of the filechooser sidebar were bad so i was unaware this
was such a problem until Kdenllive did this.

Apparently that Ubuntu Software Center has issues with all dark themes:
http://ubuntuforums.org/showthread.php?t=1913590

From that page: 

_____
1) Open up a terminal and type:
Code:

gksudo gedit /usr/share/software-center/ui/gtk3/css/softwarecenter.css

2) The first two lines should look like this:
Code:

@define-color light-aubergine #DED7DB;
@define-color super-light-aubergine #F4F1F3;

Copy and paste those two lines right below then comment out the originals. Change the two HTML color codes (#DED7DB and #F4F1F3) to your preferred dark colors so that light text will show up.

3) Save and close gedit. (or Pluma) Launch Ubuntu Software Center to check out the results

**Comment by lukefromdc** [comment] 2016-03-30 18:44
The Tkinter case appears to be an issue of a non-GTK toolkit attempting to read a theme not meant for it and reading only the text color. The rest of the displayed python-tk window clearly is not using the BlackMATE theme. Does this happen in all dark themes?  Install another dark theme and see what happens. If it happens there too you found a bug in python-tk or tk itself, which should use either all of or none of a theme not native to it.

Both the issue with the Ubuntu Software Center and the issue of QT applications not liking dark GTK themes happen with every theme that sets a dark background for views and light colored text.

**Comment by raveit65** [comment] 2016-09-25 06:19
Is this reproducible?
I'm missing also important info's like ubuntu and mate-themes version.
I will close this if reporter don't give more infos.

**Comment by raveit65** [comment] 2016-09-28 05:41
@laszlowaty 
Any answer for our questions?

**Comment by laszlowaty** [comment] 2016-09-29 19:57
@raveit65 
Give me few days and I will try to reproduce it.

**Comment by flexiondotorg** [comment] 2017-03-17 00:49
No feedback. Closing.

**Closed by flexiondotorg** 2017-03-17 00:49 UTC
