### ISSUE TITLE
Hard to trigger window resize in BlackMATE / BlueMenta

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/mate-themes#249] opened 2019-05-23 09:08 UTC
#### Expected behaviour
In the past I had no problem resizing windows by holding the mouse near the edge of the window

#### Actual behaviour
Now it seems I have to have the mouse in a pixel perfect position for BlackMATE / BlueMenta to trigger resize

See video: https://www.youtube.com/watch?v=GdwOq2uWiHI

#### Steps to reproduce the behaviour
Try to resize window

#### MATE general version
1.22.1 (Fedora 29)

#### Package version
Newest version from fedora repo as of

 23 of May 2019

#### Linux Distribution
Fedora 29 (x86_64)

**Comment by raveit65** [comment] 2019-05-23 16:40
This is BlackMate and GreenLaguna in your video, not BlueMenta.
Still wondering that you think there is a different. There are no changes in metacity themes of BlackMate and GreenLaguna.
Which version of mate-themes did you used before?

Btw. Best way to resize windows is to press alt key and resize with right mouse button (everywhere in window).
[rave@mother ~]$ gsettings get org.mate.Marco.general mouse-button-modifier
'<Alt>'

**Comment by smikkelsendk** [comment] 2019-05-23 16:59
What I wanted to show in the video was that for GreenLaguna I have no problem finding the resize area of the window, while it is almost impossible with BlackMATE (and also BlueMenta even though I did not demonstrate this). I don't think the themes themselves have changed, but something else in MATE/GTK has changed in such a way that it is now very hard to resize windows in some of the themes.

Btw. thank you for telling me about the resize shortcut - that will definitely help

**Comment by lukefromdc** [comment] 2019-05-24 03:44
This is somewhere in the Metacity theme, I was able to confirm that by using "customize" in mate-control-center>change-themes to set BlackMATE as the "window-border" style in my normal UbuntuStudio-Legacy theme
https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy
which does not have this problem.
The Metacity themes are the part of theming I understand the least however, so I was unable tonight to find the cause of this or the difference that causes only some themes to have this. Has to relate to border or margin width in some way but I was not able to find it on a quick runthrough.

**Comment by raveit65** [comment] 2019-05-24 07:03
Ok, marco-1.22.x use metacity-theme version 3 if a theme support it. This might explain differences with BlueMenta. BlueMenta is the only theme which support theme version-3 from our themes.
But GreenLaguna use version 2 and marco supports this version since a long time.
Sadly this lines in theme doesn't adjust the border from the title-bar on top of a window in video.
```
   <distance name="left_width" value="6" />
    <distance name="right_width" value="6" />
    <distance name="bottom_height" value="6" />
```
Those values are drawing only the rest of the window and increasing them doesn't increase the area to grab a window. You increase only the visible border.
Honestly, i have no idea to increase the borders of the titlebar itself. Theming of metacity themes isn't really my favorite. I tried it several times but i didn't find a way to do it.
IHMMO we should set our focus to get this PR for `invisible-borders` in code.
https://github.com/mate-desktop/marco/pull/503
This needs a bit testing but it will solve all problems with resizing windows.
It's a new feature but i am not against to consider this as bug fix and use it for 1.22 too.
I am happy to update fedora 29/30 during release cycle with this feature.

PS: porting themes to use metacity theme version 3 is an open task.

**Comment by raveit65** [comment] 2019-05-24 07:12
Opps, BlackMate uses a metacity-theme version 3 too, and they are differences.
For a quick test you can simply delete or move/save the version 3 of the them an reload marco.
If the error is gone than we need to adopt settings from version 2.

**Comment by lukefromdc** [comment] 2019-05-24 23:09
I just tested hiding the version 3 file in a "BAK" directory with no difference. We have a border width that looks like zero in BlackMATE, leading to a requirement that the cursor must be exactly on the window edge to trigger resize. Themes with a visible border do not have this problem. Still looking for the fix

**Comment by lukefromdc** [comment] 2019-05-24 23:19
This is of course true in compiz as well as in Marco, compiz-reloaded uses marco to read the themes. I hope https://github.com/mate-desktop/marco/pull/503 affects libmarco and thus compiz-reloaded as well, about to try it

**Comment by lukefromdc** [comment] 2019-05-24 23:27
https://github.com/mate-desktop/marco/pull/503
seemed to have no effect on this, if anything invisible borders seemed even harder to get the cursor to trigger resize, though that might have been chance as a 1px alignment is hard enough to get anyway

**Comment by lukefromdc** [comment] 2019-05-27 05:02
I had a little trouble diagnosing this-because it turned out I still had a second copy of mate-themes in /usr/local/share overriding my changes. 
 https://github.com/mate-desktop/mate-themes/pull/251 makes it much easier to trigger resize by providing a 5px border zone (not the 2px of metacity 1 and 2 versions) on the left and right and keeping the 6px bottom border of metacity versions 1 and 2 for version 3.

This of course does not depend on compositing to work either, unlike https://github.com/mate-desktop/marco/pull/503 which does in fact work, but only with compositing enabled and worst of all breaks building compiz-reloaded with its gtk-window-decorator that reads themes from marco

**Comment by lukefromdc** [comment] 2019-05-29 05:51
https://github.com/mate-desktop/mate-themes/pull/251 should fix this, you will need to to have the cursor within 5px instead of 1px of the borders to resize a window. 

You can apply it in place by dropping the metacity theme files metacity-theme-1.xml, metacity-theme-2.xml, metacity-theme-3.xml into the existing metacity-1 directory in /usr/share/themes/BlackMATE (or wherever your themes are installed). Alternately you can reinstall mate-themes from git master as of right now or later.

**Comment by raveit65** [comment] 2019-06-05 15:25
Re-opened, because we need to merge https://github.com/mate-desktop/mate-themes/pull/252 first,
for non compositor usage.

**Comment by raveit65** [comment] 2019-06-17 16:28
@smikkelsendk 
You should try and give karma for this update.
f29:
https://bodhi.fedoraproject.org/updates/FEDORA-2019-d6f7e0b964
f30:
https://bodhi.fedoraproject.org/updates/FEDORA-2019-c8f380b3ef

**Comment by raveit65** [comment] 2019-06-17 16:29
https://github.com/mate-desktop/mate-themes/pull/252 is merged and will be in next mate-themes release (3.22.20).

**Closed by raveit65** 2019-06-17 16:29 UTC
