### ISSUE TITLE
Blackmate makes libreoffice options menu and calc formula bar unreadable

### ISSUE THREAD

**Issue by tomracing79** [mate-desktop/mate-themes#92] opened 2015-09-07 21:47 UTC
In the libreoffice application the calc formula bar and the options menu (under Tools->Options) are unreadable white text on white background when using blackmate dark theme.
system: ArchLinux
mate desktop 1.10
libreoffice 5.0.1.2

I've included screenshots of the formula bar (highlighted to show there is text)
![calc_highlighted_white_inputbox](https://cloud.githubusercontent.com/assets/5834282/9723087/9379c838-55ba-11e5-9741-fa06e23fb414.png)
and the view i have under tools->options
![white_options_menutext](https://cloud.githubusercontent.com/assets/5834282/9723089/9c2e5598-55ba-11e5-81dc-dcdd990547c9.png)

**Comment by infirit** [comment] 2015-09-08 21:48
What Gtk+ version is your libreoffice build with? Also provide Gtk+ and mate-themes version.

**Comment by tomracing79** [comment] 2015-09-09 18:01
Thanks for the inquiry. 
in response to your questions,
looking at the buildpkg of arch
https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libreoffice-fresh
It looks like it was build using gtk2.

on my computer installed are:
mate-themes 1.10.4-1
gtk2 2.24.28-1 and 3.16.6-1

hope that helps, if you need any other input please ask

**Comment by infirit** [comment] 2015-09-09 18:51
>It looks like it was build using gtk2.

Nope, gtk3. I don't have a gtk3 enabled libreoffice atm so I can't verify this. Under Gtk2 everything is ok here.

**Comment by infirit** [comment] 2015-09-09 19:32
I can't reproduce this on my freshly update arch vm. It looks fine for me.

**Comment by NiceandGently** [comment] 2015-09-09 20:26
yes, it's a gtk3 build
https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libreoffice-fresh#n197
....and in fedora libreoffice is build with gtk2, in result i can't confirm it or try to adjust the theme.
But my experience with firefox gtk3 is that you can't style nothing specific for firefox.
I suggest to use normal gtk2 version for production.

**Comment by tomracing79** [comment] 2015-09-10 20:42
Selecting the default green theme immediately makes libre office works (see screenshot below).
guess libre office forces the formula bar and the background of the options menu colours but still takes desktop colours for the letters.

Is it more a libreoffice bug than a mate-theme bug?

![libreoffice_working_withdefaultcolors](https://cloud.githubusercontent.com/assets/5834282/9800328/b71d91da-580c-11e5-865d-8582e26e8248.png)

**Comment by monsta** [comment] 2016-03-25 12:29
Since you're using Arch, you've probably already got newer MATE and newer LO by now. Does the issue still happen for you?

**Comment by lukefromdc** [comment] 2016-03-25 17:16
In Libreoffice built with GTK3, running over GTK 3.20, BlackMATE works
fine on my system and the Calc formula bar is giving black text on a
white background.

Was this an issue with the GTK 2 portion of BlackMATE by any chance? If
so, the problem will go away for newer systems with current builds using
GTK3, though a bugfix release for older systems might be needed,

**Comment by lukefromdc** [comment] 2016-04-14 04:17
I just found that in GTK 3.20, Libreoffice gets unreadable menus (light with light text) with Adwaita and the "Traditonal" themes, while with BlackMATE, all the submarine themes, all the Menta themes, and my "UbuntuStudio_Legacy"(dark) theme, it gets dark menus with light text(good) but in one part of the 
options/Application colors window you get light text on light background. I think this is a case of an application using custom widgets not yet supporting GTK 3.20, nothing more than that.  Debian now offers GTK 3.20 in Experimental, so it will soon have it in Unstable so when Libreoffice adds support new builds should then support it. Unfortunately, this is another application that blocks GTK Inspector, so no easy way to theme it ourselves and have the ONLY themes that make it work now.

**Comment by tomracing79** [comment] 2016-04-28 21:54
For me the blackMATE theme does not give this issue anymore. Guess libre office fixed it.
Do other still have issues? if not can close the call for me.

**Comment by monsta** [comment] 2016-04-29 10:51
I'm not sure what's going on, but I see some issues in Debian Testing VM with GTK+ 3.18...

I've installed ```libreoffice-gtk``` and ```libreoffice-gtk3``` packages to check both GTK+ 2 and 3.
Here's how it looks.

GTK+2:
![libreoffice-calc-gtk2](https://cloud.githubusercontent.com/assets/5138986/14914277/cc927ada-0e19-11e6-9da9-eab5f3ce35b2.png)

GTK+3:
![libreoffice-calc-gtk3](https://cloud.githubusercontent.com/assets/5138986/14914283/d179d75a-0e19-11e6-9a2d-2b663cbe9c2a.png)

**Comment by monsta** [comment] 2016-04-29 11:00
Forgot to add that I've built mate-themes from latest 3.18 branch (as stock mate-themes in Debian Testing is somewhat outdated).

**Comment by monsta** [comment] 2016-04-29 11:10
We also have [this bug report](https://bugs.debian.org/770477) about Debian Stable (where GTK+3 is at 3.14). It's about Writer, not Calc though. Should we consider it the same issue, or a separate one?

**Comment by lukefromdc** [comment] 2016-04-29 19:53
I was unable to reproduce this in GTK 3.18 OR Gtk 3.20/21 on my systems. I did find, however, that Libreoffice is somehow caching some theme elements and not fully applying theme changes!  I found menubar selected items following my normal theme if BlackMATE was selected, but not if BlackMATE was selected and Libreoffice started up from a different user account. No idea what does this and the files required for my theme are not available from the BlackMATE theme directory. Maybe a Libreoffice bug, maybe a bug in how GTK handles URI assets?

A quick test with another user account made on GTK 3.21 stopped this and did not have the barely visible icon problem shown above, but I am not going to be able to debug Libreoffice/GTK 3.18 because I would have to reinstall several other MATE programs such as mate-panel to run GTK 3.18 and log back in as a different user.  Possibly the GTK 3.18 version of BlackMATE I have in my multiversion installation predates a commit that created this problem however, it is months old. Anyway, it won't be practical to work on that from my main system due to that theme cacheing issue that can invalidate any test on my normal user account.

Debian Testing should get GTK 3.20 shortly, its in Unstable now. Ubuntu will need this fixed but someone normally using GTK 3.18 will need to do it.

**Comment by raveit65** [comment] 2016-05-02 17:44
From the screenshot (preferences window) it looks like that settings for GtkTreeView are ignored.

**Comment by monsta** [comment] 2016-05-12 13:58
So I finally got 3.20 in my Debian Testing VM and it looks better:

![libreoffice-gtk3 20](https://cloud.githubusercontent.com/assets/5138986/15217063/e3a771d4-186a-11e6-95d3-0353d1e9c6ae.png)

Side note: the scrollbars look like they got thicker since 3.18 :smile:

**Comment by lukefromdc** [comment] 2016-05-12 16:19
Scrollbar coding completely changed between the two, though it is supposed
to be the same numbers. How much thinner should it be? It's getting more 
difficult on this end to roll back GTK versions for testing due to GTK 3.20 
specific builds.

**Comment by raveit65** [comment] 2016-09-25 06:31
As far i can see with latest LO version in f24 (3.20) they use a mix of gtk3 and gtk2 elements.
Ie. Menubar use gtk3 styling and toolbars use gtk2.
This looks for me that LO's gtk3 port isn't finished,
For me it doesn't make any sense to fix something (w/o gtk3-inspector) here until their port isn't finished.
As the origin issue is fixed i suggest to close this confusing report with several issues.

**Comment by monsta** [comment] 2016-09-25 14:32
I'm fine with closing it.

**Closed** 2016-09-25 16:44 UTC
Labels: unconfirmed
