### ISSUE TITLE
BlackMATE: Google Chrome 59 broke the URL bar

### ISSUE THREAD

**Issue by aykevl** [mate-desktop/mate-themes#182] opened 2017-06-07 16:07 UTC
Google Chrome 59 (and presumably chromium too) [switched to GTK3](https://bugs.chromium.org/p/chromium/issues/detail?id=79722#c110). That's nice, but unfortunately it made the URL bar almost unreadable:

![screenshot at 2017-06-07 17-55-31](https://user-images.githubusercontent.com/729697/26888082-36477e48-4baa-11e7-9e31-58d4e5f5ebab.png)

The menu (3 dots at the top-right) is also affected: I don't think the shortcut keys should be dark.

![screenshot at 2017-06-07 18-13-36](https://user-images.githubusercontent.com/729697/26888911-c0cd9320-4bac-11e7-98ae-50325e466de9.png)

I think other themes are also affected, but maybe not as severe. I don't remember how they looked exactly before. The non-host part of the URL is intended to look a bit less readable than the host part, so maybe it's intended behavior.

Blackbird:
![screenshot at 2017-06-07 18-04-46](https://user-images.githubusercontent.com/729697/26888501-81b6decc-4bab-11e7-918b-2853f09ce009.png)

High Contrast Inverse:
![screenshot at 2017-06-07 18-06-00](https://user-images.githubusercontent.com/729697/26888562-ac62e81e-4bab-11e7-908e-50cecb9341c7.png)

I'm using mate-themes version 3.22.11-1 from Debian stretch - unfortunately they didn't update MATE to 1.18 and are still stuck at 1.16. I hope that if there's a patch, it *might* be fixed in stretch.

**Comment by lukefromdc** [comment] 2017-06-07 17:03
I can't fix this because I do not have and cannot safely install Google Chrome on my high-privacy/high-security machines. Can someone else work on this?

**Comment by lukefromdc** [comment] 2017-06-07 17:04
https://github.com/raveit65 , can you take a look at this if you have Chrome installed?

**Comment by raveit65** [comment] 2017-06-08 05:43
gtk3-inspector does not work here....
I think the black font color comes from https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlackMATE/gtk-3.0/gtk-main.css#L22
```
@define-color theme_main_color #000000;
```
Because the menu accelerator use this color here.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlackMATE/gtk-3.0/gtk-widgets.css#L2217
```
menuitem accelerator,
menu menuitem accelerator,
.menu menuitem accelerator {
    color: alpha(@theme_main_color, 0.66);
}
```
Commenting this code block out or using another color helps a lot.
The selector is **menuitem accelerator**, but i've no idea why we use black color here.

**Comment by raveit65** [comment] 2017-06-08 06:02
The url bar use **textview text** as selector -_-
Which is defined here https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlackMATE/gtk-3.0/gtk-widgets.css#L281.
Commenting this out makes the url bar readable but breaks testview in ie. plume and firefox url bar.
Font color of firefox url bar is white without this code block.
So the issue is more that chrome url bar bg isn't light like firefox url bar.

**Comment by raveit65** [comment] 2017-06-08 06:28
The bg of the url bar is defined here
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlackMATE/gtk-3.0/gtk-widgets.css#L257 with the **view** selector.
```
view,
.view,
.view:disabled {
	background-color: @less_dark_color;
	color: @theme_selected_fg_color;
	border-radius: 0;
	/*border-width: 3;*/
}
```
Removing **view** here makes the bg of the url bar light, same like in firefox.
...don't think that makes it easier to fix it ;-)

**Comment by raveit65** [comment] 2017-06-08 06:57
Ok, we can add **textview.view** to line 281 in gtk-widget.css.
```
textview.view,
textview text,
textview.view:disabled,
GtkHTML { /* For Evolution (not enough; see entries section below) */
	background-color: @view_color;
	color: @theme_main_color;
}
```

![chrome](https://user-images.githubusercontent.com/961604/26915550-d6b73bc6-4c26-11e7-9081-370245acab53.png)

But this needs more test to see if we don't style other applications.

**Comment by aykevl** [comment] 2017-06-09 14:21
I managed to get some screenshot from an older Chrome version, for comparison.
Note that in the older version, the URL bar has a dark background.

![screenshot at 2017-06-09 16-18-10](https://user-images.githubusercontent.com/729697/26979461-28bbf336-4d2f-11e7-88bd-2ea4b1e7f258.png)
![screenshot at 2017-06-09 16-18-36](https://user-images.githubusercontent.com/729697/26979459-28b9469a-4d2f-11e7-880e-d442f039a6b0.png)
![screenshot at 2017-06-09 16-19-07](https://user-images.githubusercontent.com/729697/26979460-28ba5472-4d2f-11e7-965f-621300fbf671.png)
![screenshot at 2017-06-09 16-20-34](https://user-images.githubusercontent.com/729697/26979500-480d048c-4d2f-11e7-81a7-7e3dd655e234.png)

---

Other issues I found in the current Chrome: the search box (Ctrl+F) and (again) the keyboard shortcuts for basically any place (tab, webpage, URL bar, etc.)

**Comment by raveit65** [comment] 2017-06-09 14:41
As chrome  does not have a specific css selector, i can only use general css selectors.
So i am in doubt that i can restore a dark url bar.
Live isn't a cherry bowl ;-) 
.....and thanks to google for not using a specific css name for their product ;-)
@lukefromdc 
The dark font for menu accelerator is a general fix.

**Comment by lukefromdc** [comment] 2017-06-09 17:27
Fine by me, as a general rule I cannot maintain anything relating to software I don't use and either can't install for trust reasons or cannot spare the bandwidth to download.

**Comment by lukefromdc** [comment] 2017-06-09 17:36
I just tested this, it didn't seem to break anything else. Still lots of Firefox issues on all dark themes too-and FF is nearly impossible to maintain. Fortunately FF can also use its own themes now, maybe Chrome will follow suit and then it's just a matter of writing themes for them directly?

**Comment by lukefromdc** [comment] 2017-06-09 17:51
Just added that line to my own theme. No idea what it did before in Google Chrome and cannot test, but the code in BlackMATE came from my theme. May or may not have any effect with my default light views but why take chances when nobody is posting issues against that theme?

**Comment by raveit65** [comment] 2017-06-10 05:48
```
/* google chrome, firefox */
textview.view,
textview.view text {
    background-color: @less_dark_color;
    color: @theme_selected_fg_color;
}
```
Adding this one to the end of the section at line 333
darken the url bar of chrome and firefox.
But this makes elements of firefox unreadable.
So i won't do this as i don't have the time to fix the collateral damages for applications without gtk3-inspector and without a specific application css name.
Sorry, blame google or mozilla for this.
So let us use solution from https://github.com/mate-desktop/mate-themes/issues/182#issuecomment-307016530
I will create a branch with menu accelerator changes too.
Menu accelerator changes can be tested with our own apps .
@lukefromdc feel free to correct colors there.

**Comment by raveit65** [comment] 2017-06-10 06:02
https://github.com/mate-desktop/mate-themes/commit/7bd15bdef888a112958e9b4e45ca4440eda4f9c0
https://github.com/mate-desktop/mate-themes/commit/75e1fee028c16d5621dd8d0a183295da98e913e9
Please test.
@aykevl 
You can edit /usr/share/themes/BlackMATE/gtk-3.0/gtk-widget.css by hand for testing.
Reloading the theme is needed.

**Comment by lukefromdc** [comment] 2017-06-10 16:34
Don't have Google Chrome but no adverse effects observed in Pluma, Caja,mate-control-center, Libreoffice, or gtk3-widget-factory

**Comment by aykevl** [comment] 2017-06-10 17:02
![screenshot at 2017-06-10 18-32-07](https://user-images.githubusercontent.com/729697/27004557-27c86aa4-4e0b-11e7-834e-41c17c08c4e1.png)
Well, it doesn't look very nice, but it's now usable. I get that this is the best you can do. From my perspective, it's fixed. Thank you for the very quick fix, as usual!

I would like to raise an issue at the [Chromium project](https://bugs.chromium.org/p/chromium/issues/list) so it may be fixed properly in the future, but how should this be called? Should the window be given a special name (like "Google Chrome")?

Meanwhile I think I'll switch to Chromium in Debian, as it still appears to use GTK2 (and it finally has a built-in PDF reader!).

**Comment by raveit65** [comment] 2017-06-10 19:25
> Well, it doesn't look very nice, but it's now usable. I get that this is the best you can do. From my perspective, it's fixed. Thank you for the very quick fix, as usual!

I know, the problem are the color fonts in your screenshot, and in firefox there are much more places which are affected if you use this solution.
```
/* google chrome, firefox */
textview.view,
textview.view text {
    background-color: @less_dark_color;
    color: @theme_selected_fg_color;
}
```
 
> I would like to raise an issue at the Chromium project so it may be fixed properly in the future, but how should this be called? Should the window be given a special name (like "Google Chrome")?

If chrome would use a general **css name** at top like ie. this
```
google-chrome textview.view,
google-chrome textview.view text {
    background-color: @less_dark_color;
    color: @theme_selected_fg_color;
}
```
, than only google chrome will be styled by this line.
Please add the link to report here.
I am happy to help with a discussion with those guys.

**Comment by raveit65** [comment] 2017-06-10 19:31
> Meanwhile I think I'll switch to Chromium in Debian, as it still appears to use GTK2 (and it finally has a built-in PDF reader!).

For me google-chrome is a non-free video-player ;-)
For other usage i use good old secure firefox.

**Comment by raveit65** [comment] 2017-06-10 21:15
merged in all modern branches
https://github.com/mate-desktop/mate-themes/commit/b471395f38fa682bbc4d788703e9e3de38016310
https://github.com/mate-desktop/mate-themes/commit/bb1f13b4146eed2080c7f4b852fc4158a6973842

**Closed by raveit65** 2017-06-10 21:15 UTC

**Comment by lukefromdc** [comment] 2017-06-11 03:11
Chrome, Firefox, and Libreoffice all need to get with the program on setting css names for GTK 3.20, as few distros now use GTK 3.18 or older in new releases. Style classes are better yet, as they work with any GTK3 version

**Comment by aykevl** [comment] 2017-06-11 17:51
Here is the bug report:
https://bugs.chromium.org/p/chromium/issues/detail?id=732164

And here is the report to get this fixed in stretch:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864618

**Comment by aykevl** [comment] 2017-06-13 18:54
From [comment 5 in the Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=732164#c5):

> All widgets in Chrome already have the "chromium" style class applied to them.  Would it better/more conventional to have a base widget with name/class "chromium" instead?
> 
> Please see https://cs.chromium.org/chromium/src/docs/linux_gtk_theme_integration.md

It looks like they already have a way to target Chromium specifically (what Google Chrome is based on).

**Comment by aykevl** [comment] 2017-06-13 19:06
I have tried adding this to the bottom of `other-applications.css`:

```css

.chromium textview.view,
.chromium textview.view text {
    background-color: @less_dark_color;
    color: @theme_selected_fg_color;
}
```

This is the result:

![screenshot at 2017-06-13 21-02-19](https://user-images.githubusercontent.com/729697/27099561-a30d9636-507b-11e7-9139-967f137efd63.png)

The URL bar isn't perfect in my eyes - it has a light background and a light-gray border - but it is themable!

**Comment by lukefromdc** [comment] 2017-06-13 19:08
That looks like what we should really be using  for this and is a simple fix. Can't test it myself as usual because I don't have Chrome installed

**Comment by aykevl** [comment] 2017-06-13 19:18
I can test changes - I'll be online for a while.

**Comment by lukefromdc** [comment] 2017-06-13 20:22
Try https://github.com/mate-desktop/mate-themes/pull/185

**Comment by Cropping-static-members** [comment] 2025-01-31 18:36
https://stackdev.space/questions/having-trouble-with-applying-a-class-in-gtk3-css



It’s obvious now

**Comment by lukefromdc** [comment] 2025-01-31 20:17
I won't be able to work on any Google Chrome issues as I do not allow Chrome on any of my systems.
Maybe someone  else can fix this?
